# This is the main file that will use the Users class
from User import User


def main():
    tester()


def tester():
    """matt = User("matt")
    sarah = User("sarah")
    james = User("james")
    john = User("john")
    kylie = User("kylie")
    chris = User("chris")
    users = User.getUsers()#matt, sarah, james, john, kylie, chris]
    # Matt coaches Sarah, James, and John
    matt.addTrainee(sarah)
    matt.addTrainee(james)
    matt.addTrainee(john)
    # Kylie coaches Chris
    kylie.addTrainee(chris)
    printer(users)
    User.create_groupings()
    # # John leaves Matt to be coached by Kylie
    john.removeCoach(matt)
    kylie.addTrainee(john)
    printer(users)
    # Works with kylie
    # kylie.fullInfection(1)
    # Works with chris
    # chris.fullInfection(1)
    john.fullInfection(1)
    sarah.fullInfection(2)
    printer(users)
    User.create_groupings()"""
    zero = User("0")
    zero.addTrainee(User("1"))
    zero.addTrainee(User("2"))
    zero.addTrainee(User("3"))
    zero.addTrainee(User("4"))
    zero.addTrainee(User("5"))
    zero.addTrainee(User("6"))
    zero.addTrainee(User("7"))
    zero.addTrainee(User("8"))
    zero.addTrainee(User("9"))
    zero.addTrainee(User("10"))
    zero.addTrainee(User("11"))
    zero.addTrainee(User("12"))
    one = User("13")
    one.addTrainee(User("14"))
    one.addTrainee(User("15"))
    one.addTrainee(User("16"))
    one.addTrainee(User("17"))
    one.addTrainee(User("18"))
    one.addTrainee(User("19"))
    one.addTrainee(User("20"))
    one.addTrainee(User("21"))
    one.addTrainee(User("22"))
    one.addTrainee(User("23"))
    one.addTrainee(User("24"))
    one.addTrainee(User("25"))
    one.addTrainee(User("26"))
    one.addTrainee(User("27"))
    one.addTrainee(User("28"))
    one.addTrainee(User("29"))
    one.addTrainee(User("30"))
    one.addTrainee(User("31"))
    one.addTrainee(User("32"))
    two = User("33")
    two.addTrainee(User("34"))
    two.addTrainee(User("35"))
    two.addTrainee(User("36"))
    two.addTrainee(User("37"))
    three = User("38")
    three.addTrainee(User("39"))
    three.addTrainee(User("40"))
    three.addTrainee(User("41"))
    three.addTrainee(User("42"))
    three.addTrainee(User("43"))
    three.addTrainee(User("44"))
    three.addTrainee(User("45"))
    three.addTrainee(User("46"))
    three.addTrainee(User("47"))
    three.addTrainee(User("48"))
    three.addTrainee(User("49"))
    three.addTrainee(User("50"))
    three.addTrainee(User("51"))
    three.addTrainee(two)
    four = User("52")
    four.addTrainee(User("53"))
    four.addTrainee(User("54"))
    four.addTrainee(User("55"))
    four.addTrainee(User("56"))
    four.addTrainee(User("57"))
    four.addTrainee(User("58"))
    four.addTrainee(User("59"))
    four.addTrainee(User("60"))
    four.addTrainee(User("61"))
    four.addTrainee(User("62"))
    four.addTrainee(User("63"))
    four.addTrainee(User("64"))
    four.addTrainee(User("65"))
    four.addTrainee(User("66"))
    four.addTrainee(User("67"))
    four.addTrainee(User("68"))
    four.addTrainee(User("69"))
    four.addTrainee(User("70"))
    four.addTrainee(User("71"))
    four.addTrainee(User("72"))
    four.addTrainee(User("73"))
    four.addTrainee(User("74"))
    four.addTrainee(User("75"))
    four.addTrainee(User("76"))
    four.addTrainee(User("77"))
    four.addTrainee(User("78"))
    four.addTrainee(User("79"))
    four.addTrainee(User("80"))
    four.addTrainee(User("81"))
    four.addTrainee(User("82"))
    four.addTrainee(User("83"))
    four.addTrainee(User("84"))
    four.addTrainee(User("85"))
    four.addTrainee(User("86"))
    four.addTrainee(User("87"))
    four.addTrainee(User("88"))
    four.addTrainee(User("89"))
    four.addTrainee(User("90"))
    five = User("91")
    five.addTrainee(User("92"))
    five.addTrainee(User("93"))
    five.addTrainee(User("94"))
    five.addTrainee(User("95"))
    five.addTrainee(User("96"))
    User("97")
    User("98")
    User("99")
    users = User.getUsers()
    printer(users)
    #User.limited_infection(58, 2)
    four.fullInfection(3)
    printer(users)
    User.generateJS()

def printer(users):
    for x in users:
        print(x)
    print("*"*50)

if __name__ == "__main__":
    main()