var users = [
    {"name": "Natashia Hillery", "coaches": [], "trainees": ['Fannie Bezio', 'Sherise Kincannon', 'Mitsue Ballas', 'Angelena Barreto', 'Maxine Henrich', 'Coleen Okelly', 'Erick Magyar', 'Antonette Oppenheimer', 'Noelle Florey', 'Harriett Fleet', 'Nikia Adamczyk', 'Afton Morency', 'Delsie Wassink', 'Leonora Owusu', 'Hermina Warner', 'Dedra Sowder', 'Salvatore Elie', 'Marcell Przybylski', 'Scarlett Boyers', 'Shona Motley', 'Yahaira Knupp', 'Magali Caplinger', 'Leo Deluna', 'Alfred Espiritu', 'Minerva Bjerke'], "version": 2},
    {"name": "Fannie Bezio", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Sherise Kincannon", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Mitsue Ballas", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Angelena Barreto", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Maxine Henrich", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Coleen Okelly", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Erick Magyar", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Antonette Oppenheimer", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Noelle Florey", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Harriett Fleet", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Nikia Adamczyk", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Afton Morency", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Delsie Wassink", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Leonora Owusu", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Hermina Warner", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Dedra Sowder", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Salvatore Elie", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Marcell Przybylski", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Scarlett Boyers", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Shona Motley", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Yahaira Knupp", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Magali Caplinger", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Leo Deluna", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Alfred Espiritu", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Minerva Bjerke", "coaches": ['Natashia Hillery'], "trainees": [], "version": 2},
    {"name": "Dorine Ouzts", "coaches": [], "trainees": ['Christoper Juhasz', 'Rosendo Coffield', 'Dwight Cantor', 'Kattie Esquivel', 'Stella Beauchamp', 'Charley Fabrizio', 'Shavonne Madia', 'Dulce Maloney', 'Myesha Palin', 'Golden Laviolette', 'Dusty Clinard', 'Jacquetta Mckeighan', 'Kristie Maxon', 'Dollie Treadaway', 'Janella Borda', 'Essie Stage', 'Thresa Faust', 'Shenika Reuther'], "version": 0},
    {"name": "Christoper Juhasz", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Rosendo Coffield", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Dwight Cantor", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Kattie Esquivel", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Stella Beauchamp", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Charley Fabrizio", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Shavonne Madia", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Dulce Maloney", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Myesha Palin", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Golden Laviolette", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Dusty Clinard", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Jacquetta Mckeighan", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Kristie Maxon", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Dollie Treadaway", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Janella Borda", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Essie Stage", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Thresa Faust", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Shenika Reuther", "coaches": ['Dorine Ouzts'], "trainees": [], "version": 0},
    {"name": "Darin Styles", "coaches": [], "trainees": ['Kaitlin Brittingham', 'Yanira Klug', 'Alene Greig', 'Carlita Bartkowiak'], "version": 0},
    {"name": "Kaitlin Brittingham", "coaches": ['Darin Styles'], "trainees": [], "version": 0},
    {"name": "Yanira Klug", "coaches": ['Darin Styles'], "trainees": [], "version": 0},
    {"name": "Alene Greig", "coaches": ['Darin Styles'], "trainees": [], "version": 0},
    {"name": "Carlita Bartkowiak", "coaches": ['Darin Styles'], "trainees": [], "version": 0},
    {"name": "Jerica Albe", "coaches": [], "trainees": ['Marguerita Paez', 'Deb Wollman', 'Leonel Whalley', 'Saturnina Creason', 'Jeanette Mccallie', 'Reed Moultrie', 'Lavette Moneypenny', 'Dario Sandin', 'Dortha Mally', 'Karin Feliciano', 'Dexter Risk', 'Dorcas Portera', 'Lilliam Giancola', 'Mariela Mcquay', 'Corene Hagel', 'Celsa Teneyck', 'Roger Narron', 'Margarett Chancey', 'Luciano Portalatin', 'Jackelyn Hayes', 'Dorine Besecker', 'Jazmin Lolley', 'Temika Mathews', 'Margery Luth', 'Latasha Bodin', 'Sergio Brockett', 'Alysa Quandt', 'Stanton Pearse', 'Roosevelt Flett', 'Gwyn Drysdale', 'Britany Hilario', 'Eusebio Whittier', 'Marguerite Veach', 'Thomasina Edgley', 'Dudley Rippel', 'Marybeth Egan', 'Carmel Hanson'], "version": 3},
    {"name": "Marguerita Paez", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Deb Wollman", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Leonel Whalley", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Saturnina Creason", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Jeanette Mccallie", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Reed Moultrie", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Lavette Moneypenny", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dario Sandin", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dortha Mally", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Karin Feliciano", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dexter Risk", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dorcas Portera", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Lilliam Giancola", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Mariela Mcquay", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Corene Hagel", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Celsa Teneyck", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Roger Narron", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Margarett Chancey", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Luciano Portalatin", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Jackelyn Hayes", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dorine Besecker", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Jazmin Lolley", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Temika Mathews", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Margery Luth", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Latasha Bodin", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Sergio Brockett", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Alysa Quandt", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Stanton Pearse", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Roosevelt Flett", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Gwyn Drysdale", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Britany Hilario", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Eusebio Whittier", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Marguerite Veach", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Thomasina Edgley", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Dudley Rippel", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Marybeth Egan", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Carmel Hanson", "coaches": ['Jerica Albe'], "trainees": [], "version": 3},
    {"name": "Pierre Pilon", "coaches": [], "trainees": ['Duane Mishoe', 'Carmina Asher', 'Mai Schilling'], "version": 1},
    {"name": "Duane Mishoe", "coaches": ['Pierre Pilon'], "trainees": [], "version": 1},
    {"name": "Carmina Asher", "coaches": ['Pierre Pilon'], "trainees": [], "version": 1},
    {"name": "Mai Schilling", "coaches": ['Pierre Pilon'], "trainees": [], "version": 1},
    {"name": "Sharilyn Allaire", "coaches": [], "trainees": ['Anabel Treacy', 'Lamont Denning', 'Norberto Puga'], "version": 0},
    {"name": "Anabel Treacy", "coaches": ['Sharilyn Allaire'], "trainees": [], "version": 0},
    {"name": "Lamont Denning", "coaches": ['Sharilyn Allaire'], "trainees": [], "version": 0},
    {"name": "Norberto Puga", "coaches": ['Sharilyn Allaire'], "trainees": [], "version": 0},
    {"name": "Sofia Allard", "coaches": [], "trainees": [], "version": 4},
    {"name": "Marge Klar", "coaches": [], "trainees": [], "version": 5},
    {"name": "Virgen Temme", "coaches": [], "trainees": [], "version": 4},
    {"name": "Herschel Allgood", "coaches": [], "trainees": [], "version": 0}
];
